package com.michal.Game;

public enum Layout {
    SIXPLAYERS,
    FOURPLAYERS,
    THREEPLAYERS_ONESET,
    THREEPLAYERS_TWOSETS,
    TWOPLAYERS_ONESET,
    TWOPLAYERS_TWOSETS_ADJACENT,
    TWOPLAYERS_TWOSETS_OPPOSITE,
    TWOPLAYERS_THREESETS;
}