# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Trylma CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Ustawienie JDK
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # Budowanie i testowanie project1
    - name: server
      run: mvn -B clean verify --file server/pom.xml

    # Budowanie i testowanie project2
    - name: cli
      run: mvn -B clean verify --file client/pom.xml

    # Budowanie i testowanie project3
    - name: gui
      run: mvn -B clean verify --file gui_client/pom.xml

    - name: Update dependency graph for server
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      with:
        path: ./server/pom.xml

    - name: Update dependency graph for client
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      with:
        path: ./client/pom.xml

    - name: Update dependency graph for gui_client
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      with:
        path: ./gui_client/pom.xml
